### ISSUE TITLE
Support YAML config

### ISSUE THREAD

**Issue by bfred-it** [kentcdodds/p-s#63]
It'd be nice if p-s supported YAML configuration alongside the JS one

CommonJS files are slightly easier to read/write than JSON, but JS objects are still full `'{"\,}`

```js
module.exports = {
  scripts: {
    default: 'node index.js',
    lint: 'eslint .',
    test: {
      // learn more about Jest here: https://kcd.im/egghead-jest
      default: 'jest',
      watch: {
        script: 'jest --watch',
        description: 'run in the amazingly intelligent Jest watch mode'
      }
    },
    build: {
      default: 'webpack',
      prod: 'webpack -p',
    },
    validate: 'nps --parallel lint,test,build',
  },
}
```

in YAML it would just be

```yml
default: node index.js
lint: eslint .
test:
  # learn more about Jest here: https://kcd.im/egghead-jest
  default: jest
  watch:
    script: jest --watch
    description: run in the amazingly intelligent Jest watch mode
build:
  default: webpack
  prod: webpack -p
validate: nps --parallel lint,test,build
```

Plus, even the syntax highlighter is nicer to YAML :P

YAML isn't dynamic like JS, but probably most people don't use that (and if they do, they can just use the standard CJS syntax)
