### ISSUE TITLE
Idea: Prefixes for scripts

### ISSUE THREAD

**Issue by erikfox** [kentcdodds/p-s#85]
## This is bad:
```yaml
scripts:
  db:
    default: babel-node scripts/db.js help
    help: babel-node scripts/db.js help
    start: babel-node scripts/db.js start
    restore: babel-node scripts/db.js restore
    dump: babel-node scripts/db.js dump
    reset: babel-node scripts/db.js reset
```
👎  Serious need of DRYing
👍  1:1 for script methods = easy reading

## Current solution barely better:
```yaml
scripts:
  db:
    help: nps db help
    start: nps db start
    restore: nps db restore
    dump: nps db dump
    reset: nps db reset
    default: 
      script: babel-node scripts/db.js
      hiddenFromHelp: true
```
👎  Looks incredibly messy the more it occurs
👎  Uses up `script.default`, which I often use to auto-print help

## This would be great:
```yaml
scripts:
  db:
    _prefix: babel-node scripts/db.js
    default: help
    help: help
    start: start
    restore: restore
    dump: dump
    reset: reset
```
👍 Very DRY!
👍 Keeps default free!
👍 1:1 relationships!

Would be cool too:
```yaml
scripts:
  serve:
    _postfix: --watch
    ...
```

Just wanted to have a feasibility discussion first, willing to implement myself!
